### ISSUE TITLE
Finish CbD layer: update categories in infrastructure layer and add examples of each type of infrastructure

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#243]
- [x] New infra categories
- [ ] Descriptions of each as per descriptions in "Tool-tip" column below
- ~~Make shared footway lines a bit thinner?~~

Infrastructure Type/Name | Description/Tool-tip | Colour On Mapping | CBD Compliant |
|---|---|---|---|
| Segregated Track (wide) | Segregated Roadside Cycle Track (> min width) | Thick Dark Green | Yes |
| Off Road Cycleway | Off Road/Detached Cycle Track/Path | Thick Mid Green | Yes |
| Segregated Track (narrow) | Segregated Roadside Cycle Track (< min width/?) | Thick Light Green | Maybe/? |
| Shared Footway | Roadside Shared Pedestrian/Cycle Path/Footway | Thin Orange | Maybe/? |
| Painted Cycle Lane | On-Carriageway Cycle Lane | | |

- [ ] Examples of each 

<details>

previously we have:

![image](https://github.com/user-attachments/assets/9c4cfb94-5ad3-4b71-9fe6-3665a2d7d079)

https://github.com/nptscot/nptscot.github.io/blob/ac7d95052fac803d46e4d7e573c9e2e038ee5433/src/datasets.js#L235-L238

We should add examples of each.

**Comment by mvl22** [comment]
I will find examples of each from the CycleStreets Photomap and send the links/photos here. We have a library of 139,871 cycling/transport infrastructure images:

https://www.cyclestreets.net/photos/categories/

**Comment by mvl22** [comment]
I've found a good range of examples for each category, from the CycleStreets Photomap.

All of these images are by myself or Simon in order to avoid any copyright issues. We give permission to have them reproduced for the NPT project.

## Mixed traffic street

![cyclestreets86630-size640](https://github.com/user-attachments/assets/74666546-723e-4034-98d9-e49892237204)
https://www.cyclestreets.net/location/86630/

![cyclestreets172272-size640](https://github.com/user-attachments/assets/1899ac2f-d0ac-4e39-9cc5-e3a59ff931da)
https://www.cyclestreets.net/location/172272/

![cyclestreets14214-size640](https://github.com/user-attachments/assets/921ffe6b-9b4e-4c76-adfe-13f8bc960612)
https://www.cyclestreets.net/location/14214/

## Detached or remote cycle track

![cyclestreets92920-size640](https://github.com/user-attachments/assets/8f8d209a-0fa8-4475-98de-574d0467367f)
https://www.cyclestreets.net/location/92920/

![cyclestreets92772-size640](https://github.com/user-attachments/assets/82ed4330-2cd2-4503-8b01-1c368d6b453b)
https://www.cyclestreets.net/location/92772/

![cyclestreets81274-size640](https://github.com/user-attachments/assets/d1eb98fd-8301-4f46-891a-58e6a9e50d9a)
https://www.cyclestreets.net/location/81274/

![cyclestreets86744-size640](https://github.com/user-attachments/assets/9037a4c8-231f-4625-8ba2-f0e1bef42977)
https://www.cyclestreets.net/location/86744/

![cyclestreets175646-size640](https://github.com/user-attachments/assets/b8ec5428-dfc3-4978-bc6c-6381a287ed3f)
https://www.cyclestreets.net/location/175646/


## Cycle track at carriageway level

![cyclestreets81878-size640](https://github.com/user-attachments/assets/28142808-d2dd-45d0-a02b-c71f012455f3)
https://www.cyclestreets.net/location/81878/

![cyclestreets89775-size640](https://github.com/user-attachments/assets/2a653642-0ff6-47e5-9363-7d2675e64089)
https://www.cyclestreets.net/location/89775/

## Stepped or footway level cycle track

![cyclestreets196639-size640](https://github.com/user-attachments/assets/8d1dee40-6003-493b-bae0-ea2066c408f3)
https://www.cyclestreets.net/location/196639/

![cyclestreets57095-size640](https://github.com/user-attachments/assets/bdaaecef-26cb-4bbf-bde7-974204c18615)
https://www.cyclestreets.net/location/57095/

![cyclestreets196620-size640](https://github.com/user-attachments/assets/106c9498-1cea-4ae7-b98d-fdad826b8495)
https://www.cyclestreets.net/location/196620/

![cyclestreets191515-size640](https://github.com/user-attachments/assets/774f3f8e-63d8-4b40-b3ca-47cc139a0be0)
https://www.cyclestreets.net/location/191515/

![cyclestreets59211-size640](https://github.com/user-attachments/assets/f51c5d0f-3e4e-4607-84af-3ee38cd2c8b9)
https://www.cyclestreets.net/location/59211/

![cyclestreets197213-size1800](https://github.com/user-attachments/assets/6180b75c-be57-4906-b7ea-6230e0d277e1)
https://www.cyclestreets.net/location/197213/

## Light segregation

![cyclestreets110770-size640](https://github.com/user-attachments/assets/4014fa36-2bf7-4c7d-bfd4-b916a78ec845)
https://www.cyclestreets.net/location/110770/

![cyclestreets188865-size640](https://github.com/user-attachments/assets/5ef351c8-9bd2-4b94-bb44-84c3ade03a56)
https://www.cyclestreets.net/location/188865/


## Cycle lane

![cyclestreets81341-size640](https://github.com/user-attachments/assets/bf138750-24a6-4d30-a449-ed8d2a521d89)
https://www.cyclestreets.net/location/81341/

![cyclestreets205558-size640](https://github.com/user-attachments/assets/20b682c3-dfc7-48f4-8fce-d20c1fdc9153)
https://www.cyclestreets.net/location/205558/

![cyclestreets194549-size640](https://github.com/user-attachments/assets/b5999104-5e6f-4628-98b1-72d43d4dfe6a)
https://www.cyclestreets.net/location/194549/

![cyclestreets192579-size640](https://github.com/user-attachments/assets/62575e8a-a506-47ee-b0b5-2af47e8c3643)
https://www.cyclestreets.net/location/192579/

![cyclestreets68144-size640](https://github.com/user-attachments/assets/6d7555d0-fd8b-4e8a-8e5a-3413b78165ec)
https://www.cyclestreets.net/location/68144/

**Comment by mvl22** [comment]
I've added images for each category.

I think the purpose of this action was to determine:

- Whether the six categories in use in the guidance should form our six categories, rather than the five we have now; and then
- That our understanding of these types of infrastructure would match the OSM tag processing code - now we have examples this would be good to validate with Sustrans.

Can I suggest this ticket be moved out of the web repo as this is more about the R side.

**Comment by Robinlovelace** [comment]
Looks great but we currently have 4 categories.

**Comment by Robinlovelace** [comment]
I've added links to the 4 categories above. Will provide mapping to your categories Martin, this is helpful.

**Comment by Robinlovelace** [comment]
# NPT and CBD Classification Table

| NPT Classification            | CBD Classification                    |
|-------------------------------|----------------------------------------|
| Separated cycle track          | Detached or remote cycle track        |
| Roadside infrastructure        | Cycle track at carriageway level      |
| Roadside infrastructure        | Stepped or footway level cycle track  |
| Roadside infrastructure        | Light segregation                     |
| Cycle lane on carriageway      | Cycle lane                            |
| Mixed traffic                  | Mixed traffic street                  |

Note: we have a high bar for "detached": in the osmactive code that classifies OSM ways we set a minimum threshold distance and only above that (10 m if I recall correctly which would mean ~2 m separation for 10 m wide road and 4 m wide cycle track centrelines mapped properly) can it be called detached. That is to avoid cycleways squeezed right next to busy roads being included, like the Leeds-Bradford cycle superhighway, which should not be classified as the best type of infrastructure. Can provide photos but you've seen it already @mvl22 IRL. Make sense? Great conversation and really appreciate the concrete examples. 

It's debateable whether the first 3 images in your "Detached" examples are actually detached. Do you know how far they are from the centrelines of the nearest parallel roads in your examples (actually we use cycleway link centroids to nearest vertex on major roads in osmactive which is good at flagging junctions as not detached).

**Comment by Robinlovelace** [comment]
We have discussed all this with @anguscalder, @joeytalbot, in some detail. It's a good conversation to revisit and very glad to have input and extra thought, with reference to photos.

**Comment by mvl22** [comment]
> It's debateable whether the first 3 images in your "Detached" examples are actually detached.

Sorry, I understand the description better now. I've reallocated various photos.

Could you verify that the photos above all match the correct categories in the Cycling by Design category, before I make a further point?

PS I've included some of the Leeds-Bradford Cycleway images.

**Comment by Robinlovelace** [comment]
Yes, the photos match the CBD guidance well. However, it's important to note in our web app that the 4 NPT categories,

https://github.com/nptscot/nptscot.github.io/blob/ac7d95052fac803d46e4d7e573c9e2e038ee5433/src/datasets.js#L235-L238

Are only loosely based on the CBD. I think it's a good by @anguscalder call to collapse Cycle track at carriageway level, Stepped or footway level cycle track, and Light segregation into a single category, the reason being that there's no clear hierarchy, those categories can shift in a short distance, and because simplicity is good. So I think the docs should focus on the 4 categories above and simply state that they are based on the more detailed CBD classification with a link to that document. I don't mind including photos of the subtypes, as long as the emphasis is on the NPT classification and not the CBD classification.

Another way that NPT classification differs from CBD: the "Separated cycle track" includes any cycle infrastructure that is more than a threshold distance from **a major road**. Being Leeds-Bradford style dedicated cycleway *next to a quiet road* would make it classified as the "Separated cycle track" NPT category. Can link to the relevant code in osmactive. That is right and good I think, and has been agreed in conversations, although not adequately documented yet. This issue represents and opportunity to fix that.

**Comment by mvl22** [comment]
OK, so having got a good match of the categories to photos, and a clear description of how these are categorised, we can see that these two cases would both resolve to `Roadside infrastructure`.

As a campaigner of 20 years, I really cannot accept that the scoring of these two should be remotely similar. One is dire infrastructure, the other is highest quality Dutch standard.

So my point really is, is there a good reason to use 4 categories rather than use the definitions of the 6 categories in the guidance, which seem to be reasonably well thought out, and would mean there is then strong linkage and consistency between the guidance and the recommendations that the tools give?

![cyclestreets85724-size640](https://github.com/user-attachments/assets/2855d166-bc0e-4ae2-8cf0-c576cab22a6f)
https://www.cyclestreets.net/location/85724/

![cyclestreets81274-size640](https://github.com/user-attachments/assets/d1eb98fd-8301-4f46-891a-58e6a9e50d9a)
https://www.cyclestreets.net/location/81274/

**Comment by Robinlovelace** [comment]
Agree: the classification system should not treat the lower one as "Roadside infrastructure".

The good news is that there are tags on the cycleway and road side that can signal that this is high quality and qualitatively different from the Leeds-Bradford cycle superhighway:

- Max speed of parallel road is 20 mph not 40 mph
- The cycleway has good width: https://www.openstreetmap.org/way/394243994#map=16/51.50211/-0.10471

I think this issue belongs upstream in the osmactive repo, so have created an issue there:

**Comment by Robinlovelace** [comment]
For the non controversial ones, is there anything blocking examples being added? I think typical examples would be most useful, we can ask Sustrans Scotland for photos + ideas after we get the placeholders up is my sense.

**Comment by Robinlovelace** [comment]
https://github.com/nptscot/osmactive/issues/50

**Comment by mvl22** [comment]
> Agree: the classification system should not treat the lower one as "Roadside infrastructure".

According to your table above it should. It's certainly not the 10m type.

I think this is a clear example of why we should use the six categories in the guidance rather than arbitrarily collapse three very different ones into one. This is one of very many examples now around London and beyond.

**Comment by Robinlovelace** [comment]
> I think this is a clear example of why we should use the six categories in the guidance rather than arbitrarily collapse three very different ones into one. This is one of very many examples now around London and beyond.

@mvl22 as discussed, keeping as is or simply following the imperfect CbD guidance (for no guidance or spec is perfect, all are compromises) are not the only 2 options available to us. Will think it over, look to chat with you and others, and seek to arrive at a good solution.

My latest thinking on this is that it *is* worth having off-road and alongside infrastructure as categories, as the client has requested. Taking a step back, the biggest issue I see in the conversation above, that you rightly pointed out, is that "roadside infrastructure" is a huge category.

So I think the question is more "how do we differentiate between good and bad roadside infrastructure"? 

I have some ideas on that would like to get views from others on how best to differentiate between the types, assuming that the client wants to stick with the offroad and alongside categories, which I think is a safe default.

My guess is that the best solution will be to increase the number of categories from 4 to 5. Would you agree that the *quality* of infrastructure, e.g. as conveyed in information about width and distance from fast-moving heavy traffic, is more important than whether it's stepped, light seggregation or protected? Also looking to get input from @dabreegster and @anguscalder.

It's important to raise things and suggest changes and I appreciate that but would ask that input is constructive and open-minded.

**Comment by Robinlovelace** [comment]
Heads-up @mvl22 I'm discussing this with Angus in person now. Decisions incoming soon.

**Comment by Robinlovelace** [comment]
Decisions:

- We won't simply use the 6 categories of CbD (stepped, on carriageway separated, not on carriageway separated) as any of those 3 can be good or bad
- We'll implement the CbD definition of separated infrastructure properly (currently we're mixing some alongside infra in there)
- We'll break the Roadside infrastructure layer into 2 pieces:
  - Roadside infrastructure (Cycling by Design compliant)
  - Roadside infrasctructure (not Cycling by Design compliant / insufficient data)

**Comment by mvl22** [comment]
Sounds like a great step forward - thanks for the update.

**Comment by Robinlovelace** [comment]
Latest classification for Scotland: https://github.com/nptscot/osmactive/pull/55#issuecomment-2410497013

**Comment by Robinlovelace** [comment]
![image](https://github.com/user-attachments/assets/deda3921-6117-45af-a5d5-383210ec8ea5)

**Comment by Robinlovelace** [comment]
@mvl22 can you update the CbD layer to point here and to support the new categories? 

https://nptscot.blob.core.windows.net/pmtiles/cbd_layer_2024-10-01.pmtiles

**Comment by Robinlovelace** [comment]
Equivalent in .json format for web developer accessibility:

```json
{
  "Segregated Track (wide)": "#054d05",
  "Off Road Cycleway": "#3a9120",
  "Segregated Track (narrow)": "#87d668",
  "Shared Footway": "#ffbf00",
  "Painted Cycle Lane": "#FF0000"
}
```

**Comment by mvl22** [comment]
Great to have this dataset now.

PR #246 created.

PS For a future iteration, could you use 'Sentence case' rather than 'American Capitalised Case' for these labels - 'Painted Cycle Lane' is not a proper noun.

![Screenshot 2024-10-18 at 13 40 46](https://github.com/user-attachments/assets/90cc22da-05ca-4eae-b798-a9367ea6eeff)

**Comment by Robinlovelace** [comment]
Looks great, good enough for me, will do quick review. Follow-up question: how easy would it be to make each type toglabble? That's for another issue if we do end up doing it though.

**Comment by Robinlovelace** [comment]
@mvl22 see updated description above, 1 down, 3 to go  I think..

**Comment by mvl22** [comment]
> Follow-up question: how easy would it be to make each type toggleable?

That can be done using `filter`/`setFilter`. The nearest example can be seen here:

https://docs.mapbox.com/mapbox-gl-js/example/filter-markers/

Obviously it would need a little development work to turn this into a nice 'toggles: true' style flag in the data definition, which could then be used for any layer. Do start a new issue in due course if this turns out to be needed.

**Comment by Robinlovelace** [comment]
Thanks Martin an great to see the link to the docs. Will await feedback from Angus on whether it's needed or not. In the meantime, do you think the remaining subtasks in the updated original post in this thread are doable? I imagine tweaking line widths of the Shared Footways will be very quick, adding tooltips should be quick, adding exmamples of each time may take longer. Happy for you to take the initiative if you have ideas on how best to document/communicate the meaning of these updated categories. Will be great to be able to close this issue and move on in any case, building on great progress today.

**Comment by Robinlovelace** [comment]
National map is really interesting: 

![image](https://github.com/user-attachments/assets/6cbe117d-c3b6-4a69-ba77-d732940207dd)

Source: https://nptscot.github.io/#/clos/#8/55.953/-3.138

**Comment by mvl22** [comment]
> Make shared footway lines a bit thinner?

With the updated categories and colours I don't think this aspect should be pursued. They are already less visually prioritised, and having different line thicknesses will only add confusion I think. A shared footway isn't necessarily any narrower in practice than a dedicated track, so I think we should avoid implying that through thicknesses.

As you can see, the orange does not stand out so we shouldn't need to change its thickness:

![Screenshot 2024-10-18 at 14 19 44](https://github.com/user-attachments/assets/55775000-086e-464e-b542-c0a0a3788d0f)

![Screenshot 2024-10-18 at 14 20 18](https://github.com/user-attachments/assets/4a93c189-f1de-40b8-bd69-9da68bade0be)

**Comment by Robinlovelace** [comment]
Fine by me for now

**Comment by Robinlovelace** [comment]
:tada:
